/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.robertob.proyecto1.ipc1.frames;

import com.robertob.proyecto1.ipc1.engine.GameEngine;
import com.robertob.proyecto1.ipc1.engine.vehicles.*;
import javax.swing.JOptionPane;

/**
 *
 * @author robertob
 */
public class ChooseInitialVehicleFrame extends javax.swing.JFrame {

    GameEngine gameEngine;
    MainFrame mainFrame;
    
    public ChooseInitialVehicleFrame(GameEngine gameEngine) {
        this.gameEngine = gameEngine;
        this.mainFrame = new MainFrame(gameEngine);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectVehicleTitle1 = new javax.swing.JLabel();
        selectVehicleTitle2 = new javax.swing.JLabel();
        continueVehicleBtn = new javax.swing.JButton();
        TankVehicleToggleBtn = new javax.swing.JToggleButton();
        AirVehicleToggleBtn = new javax.swing.JToggleButton();
        tankTitle = new javax.swing.JLabel();
        planeTitle = new javax.swing.JLabel();
        youSelectedTitle = new javax.swing.JLabel();
        selectedVehicleLbl = new javax.swing.JLabel();
        vehicleNameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        selectVehicleTitle1.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        selectVehicleTitle1.setText("¡Prepárate para la batalla!");

        selectVehicleTitle2.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        selectVehicleTitle2.setText("Elige un vehiculo y dale un nombre para comenzar:");

        continueVehicleBtn.setBackground(new java.awt.Color(0, 255, 204));
        continueVehicleBtn.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        continueVehicleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/proyecto1-ipc1/images/playIcon.png"))); // NOI18N
        continueVehicleBtn.setText(" CONTINUAR");
        continueVehicleBtn.setBorderPainted(false);
        continueVehicleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueVehicleBtn.setEnabled(false);
        continueVehicleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueVehicleBtnActionPerformed(evt);
            }
        });

        TankVehicleToggleBtn.setBackground(new java.awt.Color(238, 238, 238));
        TankVehicleToggleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/proyecto1-ipc1/images/tankBlack.png"))); // NOI18N
        TankVehicleToggleBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 102), 4, true));
        TankVehicleToggleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TankVehicleToggleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TankVehicleToggleBtnActionPerformed(evt);
            }
        });

        AirVehicleToggleBtn.setBackground(new java.awt.Color(238, 238, 238));
        AirVehicleToggleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/proyecto1-ipc1/images/planeBlack.png"))); // NOI18N
        AirVehicleToggleBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 102), 4, true));
        AirVehicleToggleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AirVehicleToggleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirVehicleToggleBtnActionPerformed(evt);
            }
        });

        tankTitle.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        tankTitle.setText("TANQUE");

        planeTitle.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        planeTitle.setText("AVIÓN");

        youSelectedTitle.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        youSelectedTitle.setText("Has seleccionado:");

        selectedVehicleLbl.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N

        vehicleNameTextField.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        vehicleNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vehicleNameTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(tankTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(planeTitle)
                .addGap(196, 196, 196))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(selectVehicleTitle1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(selectVehicleTitle2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(TankVehicleToggleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(AirVehicleToggleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vehicleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(youSelectedTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectedVehicleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(continueVehicleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(selectVehicleTitle1)
                .addGap(18, 18, 18)
                .addComponent(selectVehicleTitle2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tankTitle)
                    .addComponent(planeTitle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TankVehicleToggleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AirVehicleToggleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(youSelectedTitle)
                    .addComponent(selectedVehicleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(vehicleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(continueVehicleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueVehicleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueVehicleBtnActionPerformed
        if (TankVehicleToggleBtn.isSelected()) {
            System.out.println("adding tank");
            gameEngine.getPlayer().addVehicle(new Tank(vehicleNameTextField.getText()));
            JOptionPane.showMessageDialog(this, "Comenzarás con un tanque basico con un rifle basico montado","Vehiculo agregado",JOptionPane.INFORMATION_MESSAGE);
            gameEngine.getPlayer().showAllVehicles();
            
        } else if (AirVehicleToggleBtn.isSelected()) {
            System.out.println("adding plane");
            gameEngine.getPlayer().addVehicle(new Plane(vehicleNameTextField.getText()));
            JOptionPane.showMessageDialog(this, "Comenzarás con un avion basico con un rifle basico montado","Vehiculo agregado",JOptionPane.INFORMATION_MESSAGE);
            gameEngine.getPlayer().showAllVehicles();
        }
        mainFrame.updateVehiclesList();
        this.dispose();
        mainFrame.setVisible(true);
    }//GEN-LAST:event_continueVehicleBtnActionPerformed

    private void TankVehicleToggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TankVehicleToggleBtnActionPerformed
        AirVehicleToggleBtn.setSelected(false);
        selectedVehicleLbl.setText("Tanque");
        tryEnableContinueBtn();
    }//GEN-LAST:event_TankVehicleToggleBtnActionPerformed

    private void AirVehicleToggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirVehicleToggleBtnActionPerformed
        TankVehicleToggleBtn.setSelected(false);
        selectedVehicleLbl.setText("Avión");
        tryEnableContinueBtn();
    }//GEN-LAST:event_AirVehicleToggleBtnActionPerformed

    private void vehicleNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vehicleNameTextFieldKeyTyped
        tryEnableContinueBtn();
    }//GEN-LAST:event_vehicleNameTextFieldKeyTyped

    private void tryEnableContinueBtn(){
        if((TankVehicleToggleBtn.isSelected() || AirVehicleToggleBtn.isSelected()) && !vehicleNameTextField.getText().equals("")) {
            System.out.println("(TEST) Trying to enable button...");
            continueVehicleBtn.setEnabled(true);
        } else {
            System.out.println("(TEST) Button couldnt been enabled");
            continueVehicleBtn.setEnabled(false);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AirVehicleToggleBtn;
    private javax.swing.JToggleButton TankVehicleToggleBtn;
    private javax.swing.JButton continueVehicleBtn;
    private javax.swing.JLabel planeTitle;
    private javax.swing.JLabel selectVehicleTitle1;
    private javax.swing.JLabel selectVehicleTitle2;
    private javax.swing.JLabel selectedVehicleLbl;
    private javax.swing.JLabel tankTitle;
    private javax.swing.JTextField vehicleNameTextField;
    private javax.swing.JLabel youSelectedTitle;
    // End of variables declaration//GEN-END:variables
}
