/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.robertob.proyecto1.ipc1.frames;

import com.robertob.proyecto1.ipc1.engine.GameEngine;
import com.robertob.proyecto1.ipc1.engine.vehicles.*;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author robertob
 */
public class MainFrame extends javax.swing.JFrame {

    GameEngine gameEngine;
    GameFrame gameFrame;
    String[] confirmationOptions = {"Si","No"};
    DefaultListModel vehiclesListModel = new DefaultListModel();
    Vehicle selectedVehicle;
    
    public MainFrame(GameEngine gameEngine) {
        initComponents();
        this.gameEngine = gameEngine;
        playerNicknameLbl.setText(gameEngine.getPlayer().getNickname().toUpperCase()+"?");
        gameFrame = new GameFrame(gameEngine);
    }

    public void updateVehiclesList(){
        this.vehiclesListModel.removeAllElements();
        for (int i = 0; i < 3; i++) {
            if (gameEngine.getPlayer().getVehicleIndex(i) != null) {
                vehiclesListModel.addElement(gameEngine.getPlayer().getVehicleIndex(i).getName());
            }
        }
        this.vehicleList.setModel(vehiclesListModel);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerNicknameLbl = new javax.swing.JLabel();
        readyForBattleTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        hpLbl = new javax.swing.JLabel();
        ppLbl = new javax.swing.JLabel();
        levelLbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        aimLbl = new javax.swing.JLabel();
        defenseLbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        attackLbl = new javax.swing.JLabel();
        jlabel18 = new javax.swing.JLabel();
        xpLbl = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        weaponALbl = new javax.swing.JLabel();
        weaponBLbl = new javax.swing.JLabel();
        vehicleTypeLbl = new javax.swing.JLabel();
        vehiclePicture = new javax.swing.JLabel();
        storeButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        startGameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playerNicknameLbl.setFont(new java.awt.Font("Noto Sans", 1, 22)); // NOI18N
        playerNicknameLbl.setText("PLAYER.NICKNAME?");

        readyForBattleTitle.setFont(new java.awt.Font("Noto Sans", 1, 22)); // NOI18N
        readyForBattleTitle.setText("¿LIST@ PARA LA BATALLA,");

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel1.setText("Elige uno de los vehiculos que tienes, o compra mas en la tienda para comenzar una partida:");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel2.setText("MIS VEHICULOS");

        jScrollPane1.setBorder(null);

        vehicleList.setBackground(new java.awt.Color(238, 238, 238));
        vehicleList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 175, 175), 2, true));
        vehicleList.setFont(new java.awt.Font("Noto Sans", 0, 22)); // NOI18N
        vehicleList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vehicleList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehicleListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vehicleList);

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel3.setText("ESTADO DEL VEHÍCULO | TIPO:");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel4.setText("NOMBRE:");

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel5.setText("HP:");

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel6.setText("PP:");

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel7.setText("NIVEL:");

        nameLbl.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N

        hpLbl.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N

        ppLbl.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N

        levelLbl.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel12.setText("PUNTERIA:");

        aimLbl.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N

        defenseLbl.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel15.setText("DEFENSA:");

        jLabel16.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel16.setText("ATAQUE:");

        attackLbl.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N

        jlabel18.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jlabel18.setText("XP:");

        xpLbl.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel20.setText("ARMAS:");

        weaponALbl.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N

        weaponBLbl.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ppLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(levelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlabel18)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attackLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(defenseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aimLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(weaponALbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(weaponBLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlabel18)
                                            .addComponent(xpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16))
                                    .addComponent(attackLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addComponent(defenseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(aimLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(hpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(ppLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(levelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(weaponALbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weaponBLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        vehicleTypeLbl.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N

        storeButton.setBackground(new java.awt.Color(0, 102, 102));
        storeButton.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        storeButton.setForeground(new java.awt.Color(255, 255, 255));
        storeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/proyecto1-ipc1/images/storeIconSym.png"))); // NOI18N
        storeButton.setText("ABRIR TIENDA");
        storeButton.setBorderPainted(false);
        storeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        storeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel8.setText("Abre la tienda para comprar mas vehiculos o mas armas para ellos");

        startGameButton.setBackground(new java.awt.Color(0, 255, 102));
        startGameButton.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        startGameButton.setForeground(new java.awt.Color(0, 0, 0));
        startGameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/proyecto1-ipc1/images/swordBlack.png"))); // NOI18N
        startGameButton.setText(" INICIAR PARTIDA");
        startGameButton.setBorderPainted(false);
        startGameButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(readyForBattleTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerNicknameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vehicleTypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vehiclePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(storeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(startGameButton)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerNicknameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(readyForBattleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vehicleTypeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehiclePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)
                        .addComponent(storeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(startGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vehicleListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehicleListMouseClicked
        try {
            selectedVehicle = gameEngine.getPlayer().getVehicleIndex(vehicleList.getSelectedIndex());
            gameEngine.getPlayer().setCurrentVehicle(selectedVehicle);
            setStatsText(selectedVehicle);
            
            //enableBtns
        } catch (ArrayIndexOutOfBoundsException aioobe) {
            System.out.println("No hay vehiculo seleccionado");
        }
    }//GEN-LAST:event_vehicleListMouseClicked

    private void storeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeButtonActionPerformed

    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        gameFrame.stageViewController.paintPanel();
        gameFrame.setVisible(true);
    }//GEN-LAST:event_startGameButtonActionPerformed

    private void setStatsText(Vehicle vehicle){
        nameLbl.setText(vehicle.getName());
        hpLbl.setText(String.valueOf(vehicle.getHp()));
        ppLbl.setText(String.valueOf(vehicle.getPp()));
        levelLbl.setText(String.valueOf(vehicle.getLevel()));
        xpLbl.setText(String.valueOf(vehicle.getXp()));
        attackLbl.setText(String.valueOf(vehicle.getAttack()));
        defenseLbl.setText(String.valueOf(vehicle.getDefense()));
        aimLbl.setText(String.valueOf(vehicle.getAim()));
        
        if(vehicle instanceof Tank) {
            vehicleTypeLbl.setText("TANQUE");
        } else {vehicleTypeLbl.setText("AVIÓN");}
        
        vehiclePicture.setIcon(new ImageIcon(vehicle.getImage()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aimLbl;
    private javax.swing.JLabel attackLbl;
    private javax.swing.JLabel defenseLbl;
    private javax.swing.JLabel hpLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel18;
    private javax.swing.JLabel levelLbl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel playerNicknameLbl;
    private javax.swing.JLabel ppLbl;
    private javax.swing.JLabel readyForBattleTitle;
    private javax.swing.JButton startGameButton;
    private javax.swing.JButton storeButton;
    private javax.swing.JList<String> vehicleList;
    private javax.swing.JLabel vehiclePicture;
    private javax.swing.JLabel vehicleTypeLbl;
    private javax.swing.JLabel weaponALbl;
    private javax.swing.JLabel weaponBLbl;
    private javax.swing.JLabel xpLbl;
    // End of variables declaration//GEN-END:variables
}
