/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.robertob.proyecto1.ipc1.frames;

import com.robertob.proyecto1.ipc1.engine.GameEngine;
import com.robertob.proyecto1.ipc1.engine.vehicles.Plane;
import com.robertob.proyecto1.ipc1.engine.vehicles.Tank;
import com.robertob.proyecto1.ipc1.engine.vehicles.Vehicle;
import com.robertob.proyecto1.ipc1.engine.weapons.Canon;
import com.robertob.proyecto1.ipc1.engine.weapons.MachineGun;
import com.robertob.proyecto1.ipc1.engine.weapons.Rifle;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author robertob
 */
public class StoreFrame extends javax.swing.JFrame {

    GameEngine gameEngine;
    MainFrame mainFrame;
    DefaultListModel vehiclesListModel = new DefaultListModel();
    Vehicle selectedVehicle;  
  
    public StoreFrame(GameEngine gameEngine, MainFrame mainFrame) {
        initComponents();
        this.gameEngine = gameEngine; 
        this.mainFrame = mainFrame;
        updateWeaponImpact();
    }

    public void updateVehiclesStoreList(){
        this.vehiclesListModel.removeAllElements();
        for (int i = 0; i < 3; i++) {
            if (gameEngine.getPlayer().getVehicleIndex(i) != null) {
                vehiclesListModel.addElement(gameEngine.getPlayer().getVehicleIndex(i).getName());
            }
        }
        this.vehicleList.setModel(vehiclesListModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        exitStoreButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TankVehicleToggleBtn = new javax.swing.JToggleButton();
        AirVehicleToggleBtn = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vehicleNameTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        buyVehicleButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        weaponComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        atackLbl = new javax.swing.JLabel();
        aimLbl = new javax.swing.JLabel();
        speedLbl = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleList = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        buyWeaponButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 21)); // NOI18N
        jLabel1.setText("¿QUE QUIERES COMPRAR?");

        exitStoreButton.setBackground(new java.awt.Color(255, 51, 51));
        exitStoreButton.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        exitStoreButton.setForeground(new java.awt.Color(255, 255, 255));
        exitStoreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/proyecto1-ipc1/images/exitIconSymWhite.png"))); // NOI18N
        exitStoreButton.setText("SALIR");
        exitStoreButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitStoreButton.setFocusPainted(false);
        exitStoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitStoreButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel2.setText("TIENES:");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/proyecto1-ipc1/images/gold.png"))); // NOI18N
        jLabel4.setText("99999");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jTabbedPane1.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel3.setText("TIPO DE VEHICULO");

        TankVehicleToggleBtn.setBackground(new java.awt.Color(238, 238, 238));
        TankVehicleToggleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/proyecto1-ipc1/images/tankBlack.png"))); // NOI18N
        TankVehicleToggleBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 102), 4, true));
        TankVehicleToggleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TankVehicleToggleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TankVehicleToggleBtnActionPerformed(evt);
            }
        });

        AirVehicleToggleBtn.setBackground(new java.awt.Color(238, 238, 238));
        AirVehicleToggleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/proyecto1-ipc1/images/planeBlack.png"))); // NOI18N
        AirVehicleToggleBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 102), 4, true));
        AirVehicleToggleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AirVehicleToggleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirVehicleToggleBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 19)); // NOI18N
        jLabel5.setText("Tanque");

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 19)); // NOI18N
        jLabel6.setText("Avión");

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/proyecto1-ipc1/images/helpBlack.png"))); // NOI18N
        jLabel7.setText("SOLO PUEDES TENER HASTA 3 VEHICULOS");

        vehicleNameTextField.setFont(new java.awt.Font("Open Sans", 2, 20)); // NOI18N
        vehicleNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vehicleNameTextFieldKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel8.setText("DALE UN NOMBRE");

        buyVehicleButton.setBackground(new java.awt.Color(0, 204, 153));
        buyVehicleButton.setFont(new java.awt.Font("Open Sans", 1, 22)); // NOI18N
        buyVehicleButton.setForeground(new java.awt.Color(51, 51, 51));
        buyVehicleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/proyecto1-ipc1/images/basket.png"))); // NOI18N
        buyVehicleButton.setText("COMPRAR");
        buyVehicleButton.setBorderPainted(false);
        buyVehicleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buyVehicleButton.setEnabled(false);
        buyVehicleButton.setFocusPainted(false);
        buyVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyVehicleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel6))
                            .addComponent(AirVehicleToggleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TankVehicleToggleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel5)))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buyVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(vehicleNameTextField))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(451, 451, 451))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TankVehicleToggleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(vehicleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(buyVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AirVehicleToggleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jTabbedPane1.addTab("VEHICULOS", jPanel1);

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel9.setText("¿VEHICULO?");

        weaponComboBox.setFont(new java.awt.Font("Open Sans", 0, 21)); // NOI18N
        weaponComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cañon", "Ametralladora", "Rifle" }));
        weaponComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weaponComboBoxActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel10.setText("IMPACTO");

        jLabel11.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel11.setText("ATAQUE:");

        jLabel12.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel12.setText("PUNTERIA:");

        jLabel13.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel13.setText("VELOCIDAD:");

        atackLbl.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N

        aimLbl.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N

        speedLbl.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel14.setText("ARMA");

        jScrollPane1.setBackground(new java.awt.Color(238, 238, 238));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 175, 175), 1, true));

        vehicleList.setBackground(new java.awt.Color(238, 238, 238));
        vehicleList.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        vehicleList.setForeground(new java.awt.Color(51, 51, 51));
        vehicleList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehicleListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vehicleList);

        jLabel15.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/proyecto1-ipc1/images/helpBlack.png"))); // NOI18N
        jLabel15.setText("SOLO PUEDES AÑADIR 1 ARMA MÁS EN CADA VEHICULO");

        buyWeaponButton.setBackground(new java.awt.Color(0, 204, 153));
        buyWeaponButton.setFont(new java.awt.Font("Open Sans", 1, 22)); // NOI18N
        buyWeaponButton.setForeground(new java.awt.Color(51, 51, 51));
        buyWeaponButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/proyecto1-ipc1/images/basket.png"))); // NOI18N
        buyWeaponButton.setText("COMPRAR");
        buyWeaponButton.setBorderPainted(false);
        buyWeaponButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buyWeaponButton.setEnabled(false);
        buyWeaponButton.setFocusPainted(false);
        buyWeaponButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyWeaponButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(speedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(aimLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(39, 39, 39)
                                .addComponent(atackLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(weaponComboBox, 0, 0, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(buyWeaponButton, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel15)))
                .addGap(103, 103, 103))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(weaponComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(atackLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(aimLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(speedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(buyWeaponButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("ARMAS", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("OBJETOS", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(exitStoreButton)
                .addGap(166, 166, 166)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(exitStoreButton)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TankVehicleToggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TankVehicleToggleBtnActionPerformed
        AirVehicleToggleBtn.setSelected(false);
        tryEnableBuyVehicleBtn();
    }//GEN-LAST:event_TankVehicleToggleBtnActionPerformed

    private void AirVehicleToggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirVehicleToggleBtnActionPerformed
        TankVehicleToggleBtn.setSelected(false);
        tryEnableBuyVehicleBtn();
    }//GEN-LAST:event_AirVehicleToggleBtnActionPerformed

    private void vehicleNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vehicleNameTextFieldKeyTyped
        tryEnableBuyVehicleBtn();
    }//GEN-LAST:event_vehicleNameTextFieldKeyTyped

    private void exitStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitStoreButtonActionPerformed
        this.setVisible(false);
        mainFrame.updateVehiclesList();
    }//GEN-LAST:event_exitStoreButtonActionPerformed

    private void buyVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyVehicleButtonActionPerformed
        if (mainFrame.getVehicleCount() == 3) {
            JOptionPane.showMessageDialog(this, "Ya no puedes comprar mas vehiculos!","Vehiculos llenos",JOptionPane.ERROR_MESSAGE);
        } else {
            if (TankVehicleToggleBtn.isSelected()) {
                System.out.println("adding tank");
                gameEngine.getPlayer().addVehicle(new Tank(vehicleNameTextField.getText()));
                JOptionPane.showMessageDialog(this, "Has comprado un nuevo vehiculo","Vehiculo agregado",JOptionPane.INFORMATION_MESSAGE);
                gameEngine.getPlayer().showAllVehicles();
            
            } else if (AirVehicleToggleBtn.isSelected()) {
                System.out.println("adding plane");
                gameEngine.getPlayer().addVehicle(new Plane(vehicleNameTextField.getText()));
                JOptionPane.showMessageDialog(this, "Has comprado un nuevo vehiculo","Vehiculo agregado",JOptionPane.INFORMATION_MESSAGE);
                gameEngine.getPlayer().showAllVehicles();
            }       
        }
        
        
        mainFrame.updateVehiclesList();
    }//GEN-LAST:event_buyVehicleButtonActionPerformed

    private void buyWeaponButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyWeaponButtonActionPerformed
        int selectedWeaponIndex = weaponComboBox.getSelectedIndex();
        
        if(selectedVehicle.getWeapon1() != null && selectedVehicle.getWeapon2() != null){
            JOptionPane.showMessageDialog(this, "Ya no puedes agregar mas armas!","Armas llenos",JOptionPane.ERROR_MESSAGE);
        } else {
            switch (selectedWeaponIndex) {
                case 0:
                    selectedVehicle.setWeapon2(new Canon());
                    break;
                case 1:
                    selectedVehicle.setWeapon2(new MachineGun());
                    break;
                case 2:
                    selectedVehicle.setWeapon2(new Rifle());
                    break;
                default:
                    throw new AssertionError();
                }   
        }
        
        
    }//GEN-LAST:event_buyWeaponButtonActionPerformed

    private void vehicleListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehicleListMouseClicked
        tryEnableBuyWeaponBtn();
        selectedVehicle = gameEngine.getPlayer().getVehicleIndex(vehicleList.getSelectedIndex());
    }//GEN-LAST:event_vehicleListMouseClicked

    private void weaponComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weaponComboBoxActionPerformed
        updateWeaponImpact();
    }//GEN-LAST:event_weaponComboBoxActionPerformed

    private void tryEnableBuyVehicleBtn(){
        if((TankVehicleToggleBtn.isSelected() || AirVehicleToggleBtn.isSelected()) && !vehicleNameTextField.getText().equals("")) {
            System.out.println("(TEST) Trying to enable button...");
            buyVehicleButton.setEnabled(true);
        } else {
            System.out.println("(TEST) Button couldnt been enabled");
            buyVehicleButton.setEnabled(false);
        }
    }
    
    private void tryEnableBuyWeaponBtn(){
        if (!vehicleList.isSelectionEmpty()) {
            buyWeaponButton.setEnabled(true);
        }
    }

    private void updateWeaponImpact(){
        int selectedWeaponIndex = weaponComboBox.getSelectedIndex();
        
        switch (selectedWeaponIndex) {
            case 0:
                atackLbl.setText("20");
                aimLbl.setText("0");
                speedLbl.setText("-15");
                break;
            case 1:
                atackLbl.setText("3");
                aimLbl.setText("-10");
                speedLbl.setText("15");
                break;
            case 2:
                atackLbl.setText("5");
                aimLbl.setText("5");
                speedLbl.setText("10 ");
                break;
            default:
                throw new AssertionError();
        }
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AirVehicleToggleBtn;
    private javax.swing.JToggleButton TankVehicleToggleBtn;
    private javax.swing.JLabel aimLbl;
    private javax.swing.JLabel atackLbl;
    private javax.swing.JButton buyVehicleButton;
    private javax.swing.JButton buyWeaponButton;
    private javax.swing.JButton exitStoreButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel speedLbl;
    private javax.swing.JList<String> vehicleList;
    private javax.swing.JTextField vehicleNameTextField;
    private javax.swing.JComboBox<String> weaponComboBox;
    // End of variables declaration//GEN-END:variables
}
